// A tiny deterministic catalog fixture for fast, isolated tool tests.
export const FIXTURE = {
  name: 'prism-effects-test',
  version: '9.9.9',
  generated: '2026-01-01T00:00:00.000Z',
  description: 'Test fixture catalog',
  source: 'fixture',
  galleries: [
    { id: 'charts', title: 'Charts & Metrics', count: 2 },
    { id: 'fx', title: 'FX Store', count: 1 },
  ],
  categories: ['charts / KPI'],
  tokens: {
    css: ':root{--bg:#0b0e17;--ink:#eaf1f9;--accent:#ff9900;--accent-rgb:255,153,0}',
    note: 'Include once globally.',
  },
  usage: { compose: 'insert html; include css.' },
  count: 3,
  effects: [
    {
      id: 'charts-kpi-pulse',
      name: 'Pulsing KPI Card',
      gallery: 'charts',
      galleryTitle: 'Charts & Metrics',
      category: 'KPI',
      ref: '.kpi.pulse',
      description: 'A KPI card that pulses to draw attention. Great for hero metrics.',
      classes: ['kpi', 'pulse'],
      keyframes: ['kpiPulse'],
      params: { color: 'accent' },
      componentType: 'kpi',
      tags: ['charts', 'kpi', 'animated', 'pulse'],
      usableAsBackground: false,
      needsJs: null,
      selfContained: true,
      html: '<div class="kpi pulse">$1,284,500</div>',
      // Note: shares the .shared-badge rule with fx-wind-bg to exercise dedup.
      css: '.kpi{font-size:48px;color:var(--ink)}\n.kpi.pulse{animation:kpiPulse 2s infinite}\n@keyframes kpiPulse{0%,100%{opacity:1}50%{opacity:.6}}\n.shared-badge{padding:2px 6px;border-radius:8px}',
    },
    {
      id: 'charts-kpi-delta',
      name: 'KPI Delta Tile',
      gallery: 'charts',
      galleryTitle: 'Charts & Metrics',
      category: 'KPI',
      ref: '.kpi.delta',
      description: 'A KPI tile showing a value plus a positive or negative delta.',
      classes: ['kpi', 'delta'],
      keyframes: [],
      params: null,
      componentType: 'kpi',
      tags: ['charts', 'kpi', 'delta'],
      usableAsBackground: false,
      needsJs: null,
      selfContained: true,
      html: '<div class="kpi delta">42 <span class="up">+3%</span></div>',
      css: '.kpi.delta .up{color:var(--pos,#3fb950)}\n.shared-badge{padding:2px 6px;border-radius:8px}',
    },
    {
      id: 'fx-wind-bg',
      name: 'Wind Backdrop',
      gallery: 'fx',
      galleryTitle: 'FX Store',
      category: 'Backgrounds',
      ref: '.fx-wind',
      description: 'An animated wind backdrop with drifting streaks. Usable as a page background.',
      classes: ['fx-wind'],
      keyframes: ['windDrift'],
      params: null,
      componentType: 'background',
      tags: ['fx', 'wind', 'background', 'animated'],
      usableAsBackground: true,
      needsJs: 'wind-init',
      selfContained: true,
      html: '<div class="fx-wind"></div>',
      css: '.fx-wind{position:absolute;inset:0;overflow:hidden}\n@keyframes windDrift{from{transform:translateX(-100%)}to{transform:translateX(100%)}}',
    },
  ],
};
