// Prism metadata for the official AWS Architecture Icons. build_icons.mjs merges this file into
// aws-icons.json on every build (and with --overlay-only, into the existing store in place), so a package
// refresh keeps it. Ids and artwork stay exactly as AWS ships them: this file only adds metadata, and the
// build fails if it names an id the package no longer has.
//   META: per-icon fields (aliases, short, status, endOfSupport, renamedTo, duplicateOf, note, primary, prefer)
//   XREF: per source vocabulary, a name -> icon id table. A plain id lands on that icon as xref[vocab]; an object
//         is a rule kept in the store's top-level 'rules' (resolve.mjs reads both):
//           { group: '<awd group kind>', icon? }   a container (vpc, pub, priv, sg, az, asg, acct, dc, gen...)
//           { role: 'edge'|'attr'|'meta', icon? } not drawn as a node (a relationship, folded, or not architecture)
//           { none: '<reason>' }                    known name with no icon (shut down, or absent from the package)
//           { icon, note }                          an approximate pick that carries a warning
//         plus property picks: by: '<prop>', map: { <value or value prefix>: id | rule }, standby: '<bool prop>'
//         (adds the alternate-colorway icon for a Multi-AZ standby), hint: '<shown when the prop is missing>'.
// Seeded from the interop evaluators' verified tables (draw.io 223 overrides, Python diagrams 163 rows plus its
// 59 module aliases, CloudFormation 168 types) and extended; resolve.mjs normalises everything else.

// ---- per-icon metadata, keyed by icon id (a colorway base id such as aws-res-users covers both artworks)
// aliases: abbreviations, old names and common spellings, matched whole (compact form), never as substrings
// short:   official display name when it differs from the package name (acronym form, or punctuation the file
//          names lost: "AWS X-Ray", "AWS Site-to-Site VPN")
// status:  'end-of-support' | 'retired' (absent = active), with endOfSupport (YYYY-MM-DD) and an optional note;
//          renamedTo: the icon to draw instead; duplicateOf: the canonical id of a duplicated service
// primary: the resource icon a service icon stands for (resolveIcon prefer:'resource');
// prefer:  'service' = the kit draws that primary resource with the service icon (Lambda function, DynamoDB
//          table, SQS queue, SNS topic: aws-svc-lambda 16 uses in the kit specs, aws-res-lambda-function 0)
export const META = {
  // ---- compute
  'aws-svc-ec2': { aliases: ['elastic compute cloud', 'amazon elastic compute cloud'], primary: 'aws-res-ec2-instance' },
  'aws-res-ec2-instance': { aliases: ['instance', 'ec2 instance', 'virtual machine', 'vm'] },
  'aws-res-ec2-instances': { aliases: ['ec2 instances', 'instances'] },
  'aws-res-ec2-elastic-ip-address': { aliases: ['eip', 'elastic ip'] },
  'aws-res-ec2-ami': { aliases: ['ami', 'amazon machine image', 'machine image'] },
  'aws-res-ec2-db-instance': { aliases: ['db on instance', 'database on instance'] },
  'aws-svc-ec2-auto-scaling': { aliases: ['ec2 autoscaling', 'autoscaling'] },
  'aws-svc-auto-scaling': { short: 'AWS Auto Scaling' },
  'aws-svc-ec2-image-builder': { aliases: ['image builder'] },
  'aws-svc-lambda': { aliases: ['aws lambda', 'lambda functions'], primary: 'aws-res-lambda-function', prefer: 'service' },
  'aws-svc-elastic-beanstalk': { aliases: ['beanstalk', 'eb'], primary: 'aws-res-elastic-beanstalk-application' },
  'aws-svc-app-runner': { aliases: ['apprunner'] },
  'aws-svc-serverless-application-repository': { aliases: ['sar'] },
  'aws-svc-outposts-family': { aliases: ['outposts', 'aws outposts'] },
  'aws-svc-parallel-cluster': { short: 'AWS ParallelCluster', aliases: ['parallelcluster'] },
  'aws-svc-elastic-vmware-service': { short: 'Amazon EVS', aliases: ['evs'] },
  'aws-svc-compute-optimizer': {},
  'aws-svc-aws-compute-optimizer': { duplicateOf: 'aws-svc-compute-optimizer' },
  'aws-svc-dcv': { aliases: ['nice dcv'] },
  'aws-svc-simspace-weaver': { status: 'retired', endOfSupport: '2026-03-31' },
  // ---- containers
  'aws-svc-elastic-container-service': { short: 'Amazon ECS', aliases: ['ecs'], primary: 'aws-res-elastic-container-service-service' },
  'aws-svc-elastic-kubernetes-service': { short: 'Amazon EKS', aliases: ['eks', 'kubernetes', 'k8s'] },
  'aws-svc-elastic-container-registry': { short: 'Amazon ECR', aliases: ['ecr', 'ec2 container registry', 'container registry'], primary: 'aws-res-elastic-container-registry-registry' },
  'aws-res-elastic-container-registry-registry': { aliases: ['ecr registry', 'ecr repository'] },
  'aws-res-elastic-container-registry-image': { aliases: ['ecr image', 'container image'] },
  'aws-res-elastic-container-service-task': { aliases: ['ecs task', 'task definition'] },
  'aws-res-elastic-container-service-service': { aliases: ['ecs service'] },
  'aws-res-elastic-container-service-copiiot-cli': { aliases: ['ecs copilot cli', 'copilot cli', 'copilot'] },   // AWS package typo: "copiiot"
  'aws-res-elastic-container-service-ecs-service-connect': { aliases: ['service connect'] },
  'aws-svc-red-hat-openshift-service-on-aws': { short: 'Red Hat OpenShift Service on AWS (ROSA)', aliases: ['rosa', 'openshift'] },
  // ---- storage
  'aws-svc-simple-storage-service': { short: 'Amazon S3', aliases: ['s3', 'simple storage'], primary: 'aws-res-simple-storage-service-bucket' },
  'aws-res-simple-storage-service-bucket': { aliases: ['s3 bucket', 'bucket'] },
  'aws-res-simple-storage-service-object': { aliases: ['s3 object'] },
  'aws-svc-simple-storage-service-glacier': { short: 'Amazon S3 Glacier', aliases: ['glacier', 's3 glacier'] },
  'aws-res-simple-storage-service-general-access-points': { aliases: ['s3 access points', 'access point'] },
  'aws-svc-s3-on-outposts': { aliases: ['s3 on outposts storage'] },
  'aws-svc-elastic-block-store': { short: 'Amazon EBS', aliases: ['ebs'], primary: 'aws-res-elastic-block-store-volume' },
  'aws-res-elastic-block-store-volume': { aliases: ['ebs volume'] },
  'aws-res-elastic-block-store-snapshot': { aliases: ['ebs snapshot'] },
  'aws-svc-efs': { aliases: ['elastic file system', 'amazon elastic file system'], primary: 'aws-res-elastic-file-system-file-system' },
  'aws-res-elastic-file-system-file-system': { aliases: ['efs file system'] },
  'aws-svc-fsx-for-wfs': { short: 'Amazon FSx for Windows File Server', aliases: ['fsx for windows file server', 'fsx for windows', 'fsx windows'] },
  'aws-svc-fsx-for-netapp-ontap': { aliases: ['fsx ontap', 'fsx for ontap'] },
  'aws-svc-fsx-for-lustre': { aliases: ['fsx lustre'] },
  'aws-svc-fsx-for-openzfs': { aliases: ['fsx openzfs'] },
  'aws-svc-storage-gateway': { aliases: ['sgw'] },
  'aws-svc-backup': { primary: 'aws-res-backup-vault' },
  'aws-svc-elastic-disaster-recovery': { short: 'AWS Elastic Disaster Recovery (AWS DRS)', aliases: ['drs', 'cloudendure disaster recovery'] },
  // ---- databases
  'aws-svc-rds': { aliases: ['relational database', 'relational database service'], primary: 'aws-res-aurora-rds-instance' },
  'aws-res-aurora-rds-instance': { aliases: ['rds instance', 'db instance', 'rds db instance', 'rds primary', 'rds primary instance', 'primary db instance'] },
  'aws-res-aurora-rds-instance-aternate': { aliases: ['aurora rds instance alternate', 'rds instance alternate', 'rds standby', 'rds standby instance', 'standby db instance'] },   // AWS package typo: "aternate"
  'aws-res-aurora-mysql-instance': { aliases: ['mysql', 'rds mysql', 'rds for mysql', 'mysql instance'] },
  'aws-res-aurora-postgresql-instance': { aliases: ['postgresql', 'postgres', 'rds postgresql', 'rds postgres', 'rds for postgresql', 'postgresql instance'] },
  'aws-res-aurora-mariadb-instance': { aliases: ['mariadb', 'rds mariadb', 'rds for mariadb'] },
  'aws-res-aurora-oracle-instance': { aliases: ['oracle', 'rds oracle', 'rds for oracle', 'oracle instance'] },
  'aws-res-aurora-sql-server-instance': { aliases: ['sql server', 'mssql', 'rds sql server', 'rds for sql server', 'sql server instance'] },
  'aws-res-rds-proxy-instance': { aliases: ['rds proxy'] },
  'aws-res-rds-multi-az': { aliases: ['multi az', 'rds multi az'] },
  'aws-res-rds-multi-az-db-cluster': { aliases: ['multi az db cluster'] },
  'aws-svc-aurora': { aliases: ['aurora db', 'aurora cluster'], primary: 'aws-res-aurora-instance' },
  'aws-svc-dynamodb': { aliases: ['ddb', 'dynamo'], primary: 'aws-res-dynamodb-table', prefer: 'service' },
  'aws-res-dynamodb-table': { aliases: ['dynamodb table', 'ddb table'] },
  'aws-res-dynamodb-accelerator': { aliases: ['dax', 'dynamodb dax', 'dynamodb accelerator'] },
  'aws-res-dynamodb-stream': { aliases: ['dynamodb streams'] },
  'aws-res-dynamodb-global-secondary-index': { aliases: ['gsi', 'dynamodb gsi'] },
  'aws-svc-elasticache': { primary: 'aws-res-elasticache-cache-node' },
  'aws-res-elasticache-for-redis': { aliases: ['redis', 'elasticache redis', 'elasticache for redis oss'] },
  'aws-res-elasticache-for-memcached': { aliases: ['memcached', 'elasticache memcached'] },
  'aws-res-elasticache-for-valkey': { aliases: ['valkey', 'elasticache valkey'] },
  'aws-svc-memorydb': { aliases: ['memorydb for redis'] },
  'aws-svc-documentdb': { aliases: ['docdb', 'documentdb with mongodb compatibility', 'mongodb'] },
  'aws-svc-keyspaces': { aliases: ['cassandra', 'managed apache cassandra', 'managed apache cassandra service', 'mcs'] },
  'aws-svc-database-migration-service': { short: 'AWS DMS', aliases: ['dms'] },
  'aws-svc-redshift': { aliases: ['data warehouse'] },
  // ---- networking and content delivery
  'aws-svc-virtual-private-cloud': { short: 'Amazon VPC', aliases: ['vpc'] },
  'aws-res-vpc-internet-gateway': { aliases: ['igw', 'internet gateway'] },
  'aws-res-vpc-nat-gateway': { aliases: ['nat', 'nat gw', 'ngw', 'nat gateway'] },
  'aws-res-vpc-vpn-gateway': { aliases: ['vgw', 'virtual private gateway', 'vpn gateway'] },
  'aws-res-vpc-customer-gateway': { aliases: ['cgw', 'customer gateway'] },
  'aws-res-vpc-vpn-connection': { aliases: ['vpn connection', 'vpn tunnel'] },
  'aws-res-vpc-network-access-control-list': { aliases: ['nacl', 'network acl', 'acl'] },
  'aws-res-vpc-endpoints': { aliases: ['vpce', 'vpc endpoint', 'interface endpoint', 'gateway endpoint', 'endpoint'] },
  'aws-res-vpc-peering-connection': { aliases: ['vpc peering', 'peering', 'pcx'] },
  'aws-res-vpc-elastic-network-interface': { aliases: ['eni', 'network interface', 'elastic network interface'] },
  'aws-res-vpc-elastic-network-adapter': { aliases: ['ena'] },
  'aws-res-vpc-flow-logs': { aliases: ['flow logs', 'vpc flow log'] },
  'aws-res-vpc-traffic-mirroring': { aliases: ['traffic mirroring'] },
  'aws-res-vpc-reachability-analyzer': { aliases: ['reachability analyzer'] },
  'aws-res-vpc-network-access-analyzer': { aliases: ['network access analyzer'] },
  'aws-res-vpc-carrier-gateway': { aliases: ['carrier gateway'] },
  'aws-res-route-53-route-table': { aliases: ['route table', 'rtb', 'vpc route table'] },   // the package's only route-table icon is filed under Route 53
  'aws-svc-route-53': { aliases: ['r53', 'route53', 'dns'], primary: 'aws-res-route-53-hosted-zone' },
  'aws-res-route-53-hosted-zone': { aliases: ['hosted zone', 'private hosted zone', 'public hosted zone', 'phz'] },
  // Route 53 Resolver became Route 53 VPC Resolver when Route 53 Global Resolver launched; the package kept the old file names
  'aws-res-route-53-resolver': { short: 'Route 53 VPC Resolver', aliases: ['route 53 vpc resolver', 'vpc resolver', 'route 53 resolver', 'r53 resolver', 'resolver endpoint', 'inbound endpoint', 'outbound endpoint', 'amazon provided dns'] },
  'aws-res-route-53-resolver-dns-firewall': { short: 'Route 53 VPC Resolver DNS Firewall', aliases: ['route 53 vpc resolver dns firewall', 'dns firewall', 'route 53 resolver dns firewall'] },
  'aws-res-route-53-resolver-query-logging': { short: 'Route 53 VPC Resolver query logging', aliases: ['route 53 vpc resolver query logging', 'resolver query logging', 'dns query logging'] },
  'aws-svc-cloudfront': { aliases: ['cdn'], primary: 'aws-res-cloudfront-download-distribution' },
  'aws-res-cloudfront-download-distribution': { aliases: ['cloudfront distribution', 'distribution', 'web distribution'] },
  'aws-res-cloudfront-edge-location': { aliases: ['edge location', 'point of presence', 'pop'] },
  'aws-res-cloudfront-functions': { aliases: ['cloudfront function'] },
  'aws-svc-api-gateway': { aliases: ['apigw', 'api gw', 'apigateway', 'rest api', 'http api', 'websocket api'] },
  'aws-svc-elastic-load-balancing': { short: 'Elastic Load Balancing (ELB)', aliases: ['elb', 'load balancer', 'load balancing'], primary: 'aws-res-elastic-load-balancing-application-load-balancer' },
  'aws-res-elastic-load-balancing-application-load-balancer': { aliases: ['alb', 'application load balancer', 'elbv2', 'elb application load balancer'] },
  'aws-res-elastic-load-balancing-network-load-balancer': { aliases: ['nlb', 'network load balancer'] },
  'aws-res-elastic-load-balancing-gateway-load-balancer': { aliases: ['gwlb', 'gateway load balancer'] },
  'aws-res-elastic-load-balancing-classic-load-balancer': { aliases: ['clb', 'classic load balancer', 'elb classic'] },
  'aws-svc-transit-gateway': { aliases: ['tgw'] },
  'aws-res-transit-gateway-attachment': { aliases: ['tgw attachment', 'transit gateway attachment'] },
  'aws-svc-direct-connect': { aliases: ['dx'] },
  'aws-res-direct-connect-gateway': { aliases: ['dxgw', 'dx gateway', 'direct connect gateway'] },
  'aws-svc-site-to-site-vpn': { short: 'AWS Site-to-Site VPN', aliases: ['s2s vpn', 'site to site vpn', 'ipsec vpn', 'vpn'] },
  'aws-svc-client-vpn': { aliases: ['client vpn'] },
  'aws-svc-privatelink': { aliases: ['private link', 'vpc privatelink'] },
  'aws-svc-vpc-lattice': { aliases: ['lattice'] },
  'aws-svc-cloud-wan': { aliases: ['cloudwan'] },
  'aws-svc-global-accelerator': { aliases: ['aga'] },
  'aws-svc-network-firewall': { aliases: ['anfw'] },
  'aws-res-network-firewall-endpoints': { aliases: ['firewall endpoint', 'network firewall endpoint'] },
  'aws-svc-cloud-map': { aliases: ['cloudmap'] },
  'aws-svc-application-recovery-controller': { aliases: ['arc', 'route 53 application recovery controller'] },
  'aws-svc-app-mesh': { status: 'end-of-support', endOfSupport: '2026-09-30', note: 'migrate to Amazon VPC Lattice or Amazon ECS Service Connect' },
  'aws-res-app-mesh-mesh': { status: 'end-of-support', endOfSupport: '2026-09-30' },
  'aws-res-app-mesh-virtual-gateway': { status: 'end-of-support', endOfSupport: '2026-09-30' },
  'aws-res-app-mesh-virtual-node': { status: 'end-of-support', endOfSupport: '2026-09-30' },
  'aws-res-app-mesh-virtual-router': { status: 'end-of-support', endOfSupport: '2026-09-30' },
  'aws-res-app-mesh-virtual-service': { status: 'end-of-support', endOfSupport: '2026-09-30' },
  // ---- application integration
  'aws-svc-simple-queue-service': { short: 'Amazon SQS', aliases: ['sqs'], primary: 'aws-res-simple-queue-service-queue', prefer: 'service' },
  'aws-res-simple-queue-service-queue': { aliases: ['sqs queue', 'queue', 'dead letter queue', 'dead-letter queue', 'dlq'] },
  'aws-svc-simple-notification-service': { short: 'Amazon SNS', aliases: ['sns'], primary: 'aws-res-simple-notification-service-topic', prefer: 'service' },
  'aws-res-simple-notification-service-topic': { aliases: ['sns topic', 'topic'] },
  'aws-svc-eventbridge': { aliases: ['event bridge', 'cloudwatch events'], primary: 'aws-res-eventbridge-rule' },
  'aws-res-eventbridge-rule': { aliases: ['eventbridge rule', 'event rule'] },
  'aws-res-eventbridge-scheduler': { aliases: ['eventbridge scheduler', 'scheduler'] },
  'aws-res-eventbridge-pipes': { aliases: ['eventbridge pipes', 'pipe'] },
  'aws-res-eventbridge-custom-event-bus': { aliases: ['event bus', 'custom event bus'] },
  'aws-svc-step-functions': { aliases: ['sfn', 'state machine', 'step function'] },
  'aws-svc-mq': { aliases: ['amazon mq', 'activemq', 'rabbitmq'], primary: 'aws-res-mq-broker' },
  'aws-svc-managed-workflows-for-apache-airflow': { short: 'Amazon MWAA', aliases: ['mwaa', 'airflow'] },
  // ---- analytics
  'aws-svc-opensearch-service': { aliases: ['opensearch', 'elasticsearch', 'elasticsearch service', 'amazon es'] },
  'aws-svc-quick': { aliases: ['quicksight', 'quick sight', 'quick suite', 'amazon quicksight'] },   // Amazon QuickSight is part of Amazon Quick Suite
  'aws-svc-data-firehose': { aliases: ['firehose', 'kinesis firehose', 'kinesis data firehose'] },
  'aws-svc-managed-service-for-apache-flink': { aliases: ['flink', 'kinesis data analytics', 'kinesis analytics'] },
  'aws-svc-kinesis-data-streams': { aliases: ['kds', 'kinesis stream', 'kinesis streams'] },
  'aws-svc-kinesis-video-streams': { aliases: ['kvs', 'kinesis video'] },
  'aws-svc-amazon-kinesis-video-streams': { duplicateOf: 'aws-svc-kinesis-video-streams' },
  'aws-svc-managed-streaming-for-apache-kafka': { short: 'Amazon MSK', aliases: ['msk', 'kafka', 'managed kafka', 'managed streaming for kafka'] },
  'aws-svc-emr': { aliases: ['elastic mapreduce'], primary: 'aws-res-emr-cluster' },
  'aws-svc-glue-databrew': { aliases: ['databrew'] },
  'aws-svc-cloudsearch': {},
  'aws-svc-finspace': { status: 'retired', endOfSupport: '2026-10-07' },
  // ---- security, identity, compliance
  'aws-svc-identity-and-access-management': { short: 'AWS IAM', aliases: ['iam', 'identity access management'], primary: 'aws-res-identity-access-management-role' },
  'aws-res-identity-access-management-role': { aliases: ['iam role', 'role'] },
  'aws-res-identity-access-management-permissions': { aliases: ['iam policy', 'policy', 'permissions'] },
  'aws-res-identity-access-management-sts': { aliases: ['sts', 'security token service'] },
  'aws-res-identity-access-management-iam-access-analyzer': { aliases: ['access analyzer'] },
  'aws-svc-iam-identity-center': { aliases: ['sso', 'single sign on', 'aws sso', 'identity center'] },
  'aws-svc-key-management-service': { short: 'AWS KMS', aliases: ['kms', 'kms key', 'cmk'] },
  'aws-svc-certificate-manager': { short: 'AWS Certificate Manager (ACM)', aliases: ['acm'] },
  'aws-svc-private-certificate-authority': { short: 'AWS Private CA', aliases: ['private ca', 'acm pca', 'pca'] },
  'aws-svc-secrets-manager': { aliases: ['secret', 'secrets'] },
  'aws-svc-directory-service': { aliases: ['ad', 'active directory', 'directory service'], primary: 'aws-res-directory-service-managed-microsoft-ad' },
  'aws-res-directory-service-managed-microsoft-ad': { short: 'AWS Managed Microsoft AD', aliases: ['managed microsoft ad', 'aws managed microsoft ad', 'microsoft ad', 'managed ad'] },
  'aws-res-directory-service-ad-connector': { aliases: ['ad connector'] },
  'aws-res-directory-service-simple-ad': { aliases: ['simple ad'] },
  'aws-svc-waf': { aliases: ['web application firewall', 'wafv2'] },
  'aws-svc-firewall-manager': { aliases: ['fms'] },
  'aws-svc-resource-access-manager': { short: 'AWS RAM', aliases: ['ram'] },
  'aws-svc-cloudhsm': { aliases: ['hsm'] },
  'aws-svc-verified-access': { aliases: ['ava'] },
  // ---- management and governance
  'aws-svc-cloudwatch': { aliases: ['cw'] },
  'aws-res-cloudwatch-logs': { aliases: ['cloudwatch logs', 'log group', 'cloudwatch log group'] },
  'aws-res-cloudwatch-alarm': { aliases: ['cloudwatch alarm', 'alarm'] },
  'aws-res-cloudwatch-evidently': { status: 'retired', endOfSupport: '2025-10-17' },
  'aws-svc-cloudformation': { aliases: ['cfn', 'cloud formation'], primary: 'aws-res-cloudformation-stack' },
  'aws-res-cloudformation-stack': { aliases: ['cloudformation stack', 'stack', 'nested stack'] },
  'aws-svc-cloud-development-kit': { short: 'AWS CDK', aliases: ['cdk'] },
  'aws-svc-command-line-interface': { short: 'AWS CLI', aliases: ['cli', 'aws cli'] },
  'aws-svc-systems-manager': { aliases: ['ssm'] },
  'aws-res-systems-manager-parameter-store': { aliases: ['parameter store', 'ssm parameter'] },
  'aws-res-systems-manager-session-manager': { aliases: ['session manager'] },
  'aws-svc-organizations': { aliases: ['orgs'], primary: 'aws-res-organizations-account' },
  'aws-res-organizations-account': { aliases: ['member account', 'organizations account'] },
  'aws-res-organizations-organizational-unit': { aliases: ['ou', 'organizational unit'] },
  'aws-res-organizations-management-account': { aliases: ['management account', 'payer account', 'master account'] },
  'aws-svc-health-dashboard': { aliases: ['personal health dashboard', 'phd', 'aws health'] },
  'aws-svc-well-architected-tool': { short: 'AWS Well-Architected Tool', aliases: ['well architect tool'] },
  'aws-svc-managed-service-for-prometheus': { aliases: ['amp', 'prometheus', 'managed prometheus'] },
  'aws-svc-managed-grafana': { aliases: ['amg', 'grafana', 'managed service for grafana'] },
  'aws-svc-appconfig': { aliases: ['app config', 'systems manager appconfig'] },
  'aws-svc-x-ray': { short: 'AWS X-Ray', aliases: ['xray'] },
  'aws-svc-fault-injection-service': { short: 'AWS FIS', aliases: ['fis', 'fault injection simulator'] },
  'aws-svc-chatbot': { renamedTo: 'aws-svc-q', note: 'now Amazon Q Developer in chat applications' },
  'aws-svc-management-console': {},
  // ---- developer tools
  'aws-svc-codewhisperer': { renamedTo: 'aws-svc-q', note: 'now part of Amazon Q Developer' },
  'aws-svc-infrastructure-composer': { aliases: ['application composer'] },
  'aws-svc-codepipeline': { aliases: ['code pipeline'] },
  'aws-svc-codebuild': { aliases: ['code build'] },
  'aws-svc-codecommit': { aliases: ['code commit'] },
  'aws-svc-codedeploy': { aliases: ['code deploy'] },
  // ---- machine learning
  'aws-svc-sagemaker-ai': { aliases: ['sagemaker ai'] },
  'aws-svc-augmented-ai-a2i': { short: 'Amazon A2I', aliases: ['a2i', 'augmented ai'] },
  'aws-svc-q': { aliases: ['amazon q', 'q developer', 'q business', 'amazon q developer'] },
  'aws-svc-lookout-for-vision': { status: 'retired', endOfSupport: '2025-10-31' },
  'aws-svc-panorama': { status: 'retired', endOfSupport: '2026-05-20' },
  'aws-svc-healthomics': { aliases: ['omics'] },
  'aws-svc-neuron': { aliases: ['neuron sdk', 'neuron ml sdk'] },
  // ---- migration
  'aws-svc-application-migration-service': { short: 'AWS Application Migration Service (AWS MGN)', aliases: ['mgn', 'cloudendure migration'] },
  'aws-svc-application-discovery-service': { aliases: ['ads'] },
  'aws-res-datasync-discovery': { status: 'retired', endOfSupport: '2025-05-20' },
  'aws-svc-transfer-family': { aliases: ['aws transfer', 'transfer for sftp'] },
  // ---- business applications, end user computing, customer enablement
  'aws-svc-simple-email-service': { short: 'Amazon SES', aliases: ['ses'] },
  'aws-svc-pinpoint': { status: 'end-of-support', endOfSupport: '2026-10-30', note: 'messaging continues in AWS End User Messaging' },
  'aws-res-pinpoint-journey': { status: 'end-of-support', endOfSupport: '2026-10-30' },
  'aws-svc-pinpoint-apis': { renamedTo: 'aws-svc-end-user-messaging', note: 'the Pinpoint SMS, voice and push APIs are now AWS End User Messaging' },
  'aws-svc-workdocs': { status: 'retired', endOfSupport: '2025-04-25' },
  'aws-svc-workdocs-sdk': { status: 'retired', endOfSupport: '2025-04-25' },
  'aws-svc-iq': { status: 'retired', endOfSupport: '2026-05-20' },
  'aws-svc-repost': { short: 'AWS re:Post' },
  'aws-svc-repost-private': { short: 'AWS re:Post Private' },
  'aws-svc-training-certification': { short: 'AWS Training and Certification' },
  // ---- IoT, media
  'aws-svc-iot-core': { aliases: ['aws iot', 'iot'] },
  'aws-svc-iot-events': { status: 'retired', endOfSupport: '2026-05-20' },
  'aws-res-iot-device-management-fleet-hub': { status: 'retired', endOfSupport: '2025-10-18' },
  'aws-svc-elemental-mediastore': { status: 'retired', endOfSupport: '2025-11-12' },
  'aws-svc-gamelift-servers': { aliases: ['gamelift'] },
  'aws-svc-interactive-video-service': { short: 'Amazon IVS', aliases: ['ivs', 'interactive video'] },
  // ---- general resource icons (official -dark/-light pairs, addressed by the base id)
  'aws-res-client': { aliases: ['browser', 'web browser', 'desktop client'] },
  'aws-res-mobile-client': { aliases: ['mobile app', 'mobile device'] },
  'aws-res-office-building': { aliases: ['office'] },
  'aws-res-server': { aliases: ['traditional server', 'on premises server', 'on prem server'] },
  'aws-res-database': { aliases: ['generic database'] },
  'aws-res-firewall': { aliases: ['generic firewall'] },
  'aws-svc-marketplace': { short: 'AWS Marketplace' },
};

// ---- names per source vocabulary (matched case-insensitively). Only names the normaliser in resolve.mjs
// cannot derive (renames, acronyms, category headers, retired services) need an entry, except cfn and tf,
// whose type names are listed in full.
export const XREF = {
  // draw.io AWS4 library: resIcon=mxgraph.aws4.<name> service tiles and shape=mxgraph.aws4.<name> resource shapes
  drawio: {
    s3: 'aws-svc-simple-storage-service', sns: 'aws-svc-simple-notification-service', sqs: 'aws-svc-simple-queue-service',
    ec2: 'aws-svc-ec2', ecs: 'aws-svc-elastic-container-service', eks: 'aws-svc-elastic-kubernetes-service',
    ecr: 'aws-svc-elastic-container-registry', efs: 'aws-svc-efs', elastic_file_system: 'aws-svc-efs',
    elastic_block_store: 'aws-svc-elastic-block-store', rds: 'aws-svc-rds', vpc: 'aws-svc-virtual-private-cloud',
    vpc_privatelink: 'aws-svc-privatelink', iam: 'aws-svc-identity-and-access-management',
    identity_and_access_management: 'aws-svc-identity-and-access-management', single_sign_on: 'aws-svc-iam-identity-center',
    kms: 'aws-svc-key-management-service', cloudwatch_2: 'aws-svc-cloudwatch', cloudwatch: 'aws-svc-cloudwatch',
    elasticsearch_service: 'aws-svc-opensearch-service', kinesis_data_firehose: 'aws-svc-data-firehose',
    kinesis_data_streams: 'aws-svc-kinesis-data-streams', auto_scaling2: 'aws-svc-auto-scaling',
    auto_scaling3: 'aws-svc-ec2-auto-scaling', autoscaling: 'aws-svc-auto-scaling', app_config: 'aws-svc-appconfig',
    xray: 'aws-svc-x-ray', fsx_for_windows_file_server: 'aws-svc-fsx-for-wfs', glacier: 'aws-svc-simple-storage-service-glacier',
    certificate_manager_3: 'aws-svc-certificate-manager', codeguru_2: 'aws-svc-codeguru',
    elastic_inference_2: 'aws-svc-elastic-inference', rekognition_2: 'aws-svc-rekognition', sagemaker_2: 'aws-svc-sagemaker',
    gamelift_2: 'aws-svc-gamelift-servers', open_3d_engine_2: 'aws-svc-open-3d-engine', nova2: 'aws-svc-nova',
    quick_suite: 'aws-svc-quick', documentdb_with_mongodb_compatibility: 'aws-svc-documentdb',
    managed_apache_cassandra_service: 'aws-svc-keyspaces', memorydb_for_redis: 'aws-svc-memorydb',
    managed_streaming_for_kafka: 'aws-svc-managed-streaming-for-apache-kafka', step_functions: 'aws-svc-step-functions',
    express_workflow: 'aws-svc-express-workflows', application_composer: 'aws-svc-infrastructure-composer',
    command_line_interface: 'aws-svc-command-line-interface', personal_health_dashboard: 'aws-svc-health-dashboard',
    nice_dcv: 'aws-svc-dcv', fault_injection_simulator: 'aws-svc-fault-injection-service', outposts: 'aws-svc-outposts-family',
    outposts_1u_and_2u_servers: 'aws-svc-outposts-servers', cloudendure_disaster_recovery: 'aws-svc-elastic-disaster-recovery',
    cloudendure_migration: 'aws-svc-application-migration-service', tensorflow_on_aws: 'aws-svc-tensorflow-on-aws',
    torchserve: 'aws-svc-pytorch-on-aws', augmented_ai: 'aws-svc-augmented-ai-a2i', neuron_ml_sdk: 'aws-svc-neuron',
    omics: 'aws-svc-healthomics', interactive_video: 'aws-svc-interactive-video-service',
    well_architect_tool: 'aws-svc-well-architected-tool', budgets_2: 'aws-svc-budgets', mq: 'aws-svc-mq',
    lightsail_for_research: 'aws-svc-lightsail-for-research', internet_of_things: 'aws-svc-iot-core',
    greengrass: 'aws-svc-iot-greengrass', console_mobile_application: 'aws-svc-console-mobile-application',
    transform: 'aws-svc-transform', cloudsearch2: 'aws-svc-cloudsearch', managed_service_for_grafana: 'aws-svc-managed-grafana',
    s3_on_outposts_storage: 'aws-svc-s3-on-outposts', marketplace: 'aws-svc-marketplace',
    elemental: 'aws-svc-elemental-appliances-software', analytics: 'aws-cat-analytics',
    application_integration: 'aws-cat-application-integration', blockchain: 'aws-cat-blockchain',
    business_application: 'aws-cat-business-applications', cost_management: 'aws-cat-cloud-financial-management',
    compute: 'aws-cat-compute', containers: 'aws-cat-containers', customer_enablement: 'aws-cat-customer-enablement',
    database: 'aws-cat-databases', developer_tools: 'aws-cat-developer-tools',
    desktop_and_app_streaming: 'aws-cat-end-user-computing', mobile: 'aws-cat-front-end-web-mobile', games: 'aws-cat-games',
    internet_of_things_cat: 'aws-cat-internet-of-things', machine_learning: 'aws-cat-artificial-intelligence',
    management_and_governance: 'aws-cat-management-tools', media_services: 'aws-cat-media-services',
    migration_and_transfer: 'aws-cat-migration-modernization', multicloud_and_hybrid: 'aws-cat-multicloud-and-hybrid',
    networking_and_content_delivery: 'aws-cat-networking-content-delivery', quantum_technologies: 'aws-cat-quantum-technologies',
    satellite: 'aws-cat-satellite', security_identity_and_compliance: 'aws-cat-security-identity', storage: 'aws-cat-storage',
    serverless: 'aws-cat-serverless', lambda_function: 'aws-res-lambda-function', instance2: 'aws-res-ec2-instance',
    instance: 'aws-res-ec2-instance', instances: 'aws-res-ec2-instances', rds_instance: 'aws-res-aurora-rds-instance',
    rds_mysql_instance: 'aws-res-aurora-mysql-instance', rds_postgresql_instance: 'aws-res-aurora-postgresql-instance',
    rds_oracle_instance: 'aws-res-aurora-oracle-instance', rds_sql_server_instance: 'aws-res-aurora-sql-server-instance',
    rds_mariadb_instance: 'aws-res-aurora-mariadb-instance', aurora_instance: 'aws-res-aurora-instance',
    rds_proxy: 'aws-res-rds-proxy-instance', rds_multi_az: 'aws-res-rds-multi-az',
    elastic_ip_address: 'aws-res-ec2-elastic-ip-address', ami: 'aws-res-ec2-ami', spot_instance: 'aws-res-ec2-spot-instance',
    internet_gateway: 'aws-res-vpc-internet-gateway', nat_gateway: 'aws-res-vpc-nat-gateway',
    vpn_gateway: 'aws-res-vpc-vpn-gateway', vpn_connection: 'aws-res-vpc-vpn-connection',
    customer_gateway: 'aws-res-vpc-customer-gateway', endpoints: 'aws-res-vpc-endpoints', endpoint: 'aws-res-vpc-endpoints',
    peering: 'aws-res-vpc-peering-connection', elastic_network_interface: 'aws-res-vpc-elastic-network-interface',
    flow_logs: 'aws-res-vpc-flow-logs', network_access_control_list: 'aws-res-vpc-network-access-control-list',
    router: 'aws-res-vpc-router', route_table: 'aws-res-route-53-route-table',
    transit_gateway_attachment: 'aws-res-transit-gateway-attachment',
    vpc_virtual_private_cloud_vpc: 'aws-res-vpc-virtual-private-cloud-vpc',
    application_load_balancer: 'aws-res-elastic-load-balancing-application-load-balancer',
    network_load_balancer: 'aws-res-elastic-load-balancing-network-load-balancer',
    gateway_load_balancer: 'aws-res-elastic-load-balancing-gateway-load-balancer',
    classic_load_balancer: 'aws-res-elastic-load-balancing-classic-load-balancer', hosted_zone: 'aws-res-route-53-hosted-zone',
    download_distribution: 'aws-res-cloudfront-download-distribution', edge_location: 'aws-res-cloudfront-edge-location',
    role: 'aws-res-identity-access-management-role', permissions: 'aws-res-identity-access-management-permissions',
    sts: 'aws-res-identity-access-management-sts', mfa_token: 'aws-res-identity-access-management-mfa-token',
    managed_ms_ad: 'aws-res-directory-service-managed-microsoft-ad',
    aws_managed_microsoft_ad: 'aws-res-directory-service-managed-microsoft-ad',
    ad_connector: 'aws-res-directory-service-ad-connector', organizations_account: 'aws-res-organizations-account',
    organizations_organizational_unit: 'aws-res-organizations-organizational-unit',
    organizations_management_account: 'aws-res-organizations-management-account',
    network_firewall_endpoints: 'aws-res-network-firewall-endpoints', bucket: 'aws-res-simple-storage-service-bucket',
    bucket_with_objects: 'aws-res-simple-storage-service-bucket-with-objects', object: 'aws-res-simple-storage-service-object',
    topic: 'aws-res-simple-notification-service-topic', queue: 'aws-res-simple-queue-service-queue',
    message: 'aws-res-simple-queue-service-message', dynamodb_table: 'aws-res-dynamodb-table', table: 'aws-res-dynamodb-table',
    dynamodb_stream: 'aws-res-dynamodb-stream', dynamodb_dax: 'aws-res-dynamodb-accelerator',
    eventbridge_default_event_bus_resource: 'aws-res-eventbridge-default-event-bus',
    eventbridge_custom_event_bus_resource: 'aws-res-eventbridge-custom-event-bus', rule_3: 'aws-res-eventbridge-rule',
    eventbridge_saas_partner_event_bus_resource: 'aws-res-eventbridge-saas-partner-event',
    ecs_task: 'aws-res-elastic-container-service-task', ecs_service: 'aws-res-elastic-container-service-service',
    container_1: 'aws-res-elastic-container-service-container-1',
    container_registry_image: 'aws-res-elastic-container-registry-image', registry: 'aws-res-elastic-container-registry-registry',
    stack: 'aws-res-cloudformation-stack', template: 'aws-res-cloudformation-template',
    change_set: 'aws-res-cloudformation-change-set', alarm: 'aws-res-cloudwatch-alarm', cloudwatch_logs: 'aws-res-cloudwatch-logs',
    parameter_store: 'aws-res-systems-manager-parameter-store', cache_node: 'aws-res-elasticache-cache-node',
    elasticache_for_redis: 'aws-res-elasticache-for-redis', users: 'aws-res-users', user: 'aws-res-user', client: 'aws-res-client',
    mobile_client: 'aws-res-mobile-client', office_building: 'aws-res-office-building',
    corporate_data_center: 'aws-res-office-building', traditional_server: 'aws-res-server', servers: 'aws-res-servers',
    internet: 'aws-res-internet', internet_alt1: 'aws-res-internet-alt1', globe: 'aws-res-globe',
    generic_database: 'aws-res-database', disk: 'aws-res-disk', document: 'aws-res-document', documents: 'aws-res-documents',
    folder: 'aws-res-folder', email_2: 'aws-res-email', generic_firewall: 'aws-res-firewall', saml_token: 'aws-res-saml-token',
    ssl_padlock: 'aws-res-ssl-padlock', source_code: 'aws-res-source-code', git_repository: 'aws-res-git-repository',
    tape_storage: 'aws-res-tape-storage', logs: 'aws-res-logs', metrics: 'aws-res-metrics', gear: 'aws-res-gear',
    credentials: 'aws-res-credentials', management_console2: 'aws-res-management-console',
    authenticated_user: 'aws-res-authenticated-user', data_table: 'aws-res-data-table', data_stream: 'aws-res-data-stream',
    alert: 'aws-res-alert', generic_application: 'aws-res-generic-application', multimedia: 'aws-res-multimedia',
    question: 'aws-res-question', recover: 'aws-res-recover', programming_language: 'aws-res-programming-language',
    magnifying_glass_2: 'aws-res-magnifying-glass', cold_storage: 'aws-res-cold-storage', chat: 'aws-res-chat',
    camera2: 'aws-res-camera', external_toolkit: 'aws-res-toolkit', external_sdk: 'aws-res-sdk', shield2: 'aws-res-shield',
    forums: 'aws-res-forums', json_script: 'aws-res-json-script',
    // draw.io illustrations have no AWS icon: the nearest general icon, with a warning
    illustration_users: { icon: 'aws-res-users', note: 'approximate: draw.io illustration' },
    illustration_notification: { icon: 'aws-res-alert', note: 'approximate: draw.io illustration' },
    illustration_devices: { icon: 'aws-res-mobile-client', note: 'approximate: draw.io illustration' },
    illustration_desktop: { icon: 'aws-res-client', note: 'approximate: draw.io illustration' },
    illustration_office_building: { icon: 'aws-res-office-building', note: 'approximate: draw.io illustration' },
    // group frames (grIcon=mxgraph.aws4.<name>); draw.io draws subnets with group_security_group, green when public
    group_aws_cloud: { group: 'cloud' }, group_aws_cloud_alt: { group: 'cloud' }, group_region: { group: 'region' },
    group_vpc: { group: 'vpc' }, group_vpc2: { group: 'vpc' }, group_availability_zone: { group: 'az' },
    group_security_group: { group: 'priv', by: 'strokeColor', map: { '#7aa116': { group: 'pub' }, '#248814': { group: 'pub' } }, hint: 'draw.io strokes public subnets green (#7AA116), private ones teal or blue' },
    group_auto_scaling_group: { group: 'asg' }, group_account: { group: 'acct' }, group_corporate_data_center: { group: 'dc' },
    group_on_premise: { group: 'server' }, group_ec2_instance_contents: { group: 'ec2' }, group_spot_fleet: { group: 'spot' },
    group_elastic_beanstalk: { group: 'gen', icon: 'aws-svc-elastic-beanstalk' }, group_aws_step_functions_workflow: { group: 'gen', icon: 'aws-svc-step-functions' },
    group_iot_greengrass: { group: 'gen', icon: 'aws-svc-iot-greengrass' }, group_iot_greengrass_deployment: { group: 'gen', icon: 'aws-grp-iot-greengrass-deployment' },
  },
  // awslabs aws-icons-for-plantuml pack keys as Mermaid uses them (aws:<key>, kebab case of the PlantUML macro)
  mermaid: {
    'migration-hub': { none: 'AWS Migration Hub has no icon in the Q3 2026 package' },
  },
  // aws-icons-for-plantuml macros (icons resolve by name; the group macros are frames)
  plantuml: {
    AWSCloudGroup: { group: 'cloud' }, AWSCloudAltGroup: { group: 'cloud' }, RegionGroup: { group: 'region' },
    AvailabilityZoneGroup: { group: 'az' }, SecurityGroupGroup: { group: 'sg' }, AutoScalingGroupGroup: { group: 'asg' },
    VPCGroup: { group: 'vpc' }, PublicSubnetGroup: { group: 'pub' }, PrivateSubnetGroup: { group: 'priv' },
    ServerContentsGroup: { group: 'server' }, CorporateDataCenterGroup: { group: 'dc' }, EC2InstanceContentsGroup: { group: 'ec2' },
    SpotFleetGroup: { group: 'spot' }, AWSAccountGroup: { group: 'acct' }, GenericGroup: { group: 'gen' }, GenericAltGroup: { group: 'gen' },
    ElasticBeanstalkContainerGroup: { group: 'gen', icon: 'aws-svc-elastic-beanstalk' }, StepFunctionsWorkflowGroup: { group: 'gen', icon: 'aws-svc-step-functions' },
    IoTGreengrassGroup: { group: 'gen', icon: 'aws-svc-iot-greengrass' }, IoTGreengrassDeploymentGroup: { group: 'gen', icon: 'aws-grp-iot-greengrass-deployment' },
  },
  // Python diagrams (mingrammer), module-qualified: <module>.<Class> for diagrams.aws.<module>.<Class>
  diagrams: {
    'compute.EC2ContainerRegistryImage': 'aws-res-elastic-container-registry-image',
    'compute.EC2ContainerRegistryRegistry': 'aws-res-elastic-container-registry-registry',
    'compute.EC2ContainerRegistry': 'aws-svc-elastic-container-registry',
    'compute.ElasticContainerServiceContainer': 'aws-res-elastic-container-service-container-1',
    'compute.ElasticContainerServiceServiceConnect': 'aws-res-elastic-container-service-ecs-service-connect',
    'compute.Outposts': 'aws-svc-outposts-family', 'compute.ThinkboxDraft': { none: 'no icon in the AWS package' },
    'compute.ThinkboxSequoia': { none: 'no icon in the AWS package' },
    'compute.VmwareCloudOnAWS': { none: 'VMware Cloud on AWS has no icon in the package (Amazon EVS is a different product)' }, 'compute.Compute': 'aws-cat-compute',
    'compute.LambdaFunction': 'aws-res-lambda-function',
    'network.ElbApplicationLoadBalancer': 'aws-res-elastic-load-balancing-application-load-balancer',
    'network.ElbClassicLoadBalancer': 'aws-res-elastic-load-balancing-classic-load-balancer',
    'network.ElbNetworkLoadBalancer': 'aws-res-elastic-load-balancing-network-load-balancer',
    'network.Nacl': 'aws-res-vpc-network-access-control-list',
    'network.NetworkingAndContentDelivery': 'aws-cat-networking-content-delivery',
    'network.VPCPeering': 'aws-res-vpc-peering-connection', 'network.VPC': 'aws-svc-virtual-private-cloud',
    'network.Endpoint': 'aws-res-vpc-endpoints', 'network.PublicSubnet': 'aws-grp-public-subnet',
    'network.PrivateSubnet': 'aws-grp-private-subnet', 'network.RouteTable': 'aws-res-route-53-route-table',
    'database.DatabaseMigrationServiceDatabaseMigrationWorkflow': 'aws-res-database-migration-service-database-migration-workflow-or-job',
    'database.DocumentdbMongodbCompatibility': 'aws-svc-documentdb', 'database.DynamodbDax': 'aws-res-dynamodb-accelerator',
    'database.DynamodbStreams': 'aws-res-dynamodb-stream', 'database.KeyspacesManagedApacheCassandraService': 'aws-svc-keyspaces',
    'database.QuantumLedgerDatabaseQldb': { none: 'Amazon QLDB shut down 2025-07-31' },
    'database.RDSMariadbInstance': 'aws-res-aurora-mariadb-instance', 'database.RDSMysqlInstance': 'aws-res-aurora-mysql-instance',
    'database.RDSOracleInstance': 'aws-res-aurora-oracle-instance',
    'database.RDSPostgresqlInstance': 'aws-res-aurora-postgresql-instance',
    'database.RDSSqlServerInstance': 'aws-res-aurora-sql-server-instance', 'database.RDSOnVmware': { none: 'Amazon RDS on VMware shut down' },
    'database.Database': 'aws-res-database', 'database.RDSInstance': 'aws-res-aurora-rds-instance',
    'storage.CloudendureDisasterRecovery': 'aws-svc-elastic-disaster-recovery',
    'storage.EFSInfrequentaccessPrimaryBg': 'aws-res-elastic-file-system-efs-standard-infrequent-access',
    'storage.EFSStandardPrimaryBg': 'aws-res-elastic-file-system-efs-standard', 'storage.ElasticFileSystemEFS': 'aws-svc-efs',
    'storage.FsxForWindowsFileServer': 'aws-svc-fsx-for-wfs',
    'storage.S3AccessPoints': 'aws-res-simple-storage-service-general-access-points',
    'storage.S3GlacierArchive': 'aws-res-simple-storage-service-glacier-archive',
    'storage.S3GlacierVault': 'aws-res-simple-storage-service-glacier-vault',
    'storage.S3Glacier': 'aws-svc-simple-storage-service-glacier',
    'storage.SnowFamilySnowballImportExport': 'aws-res-snowball-import-export', 'storage.Snowmobile': { none: 'AWS Snowmobile shut down' },
    'storage.Storage': 'aws-cat-storage', 'integration.ApplicationIntegration': 'aws-cat-application-integration',
    'integration.EventResource': 'aws-res-eventbridge-event',
    'integration.EventbridgeSaasPartnerEventBusResource': 'aws-res-eventbridge-saas-partner-event',
    'security.SecurityIdentityAndCompliance': 'aws-cat-security-identity', 'security.SingleSignOn': 'aws-svc-iam-identity-center',
    'security.Artifact': 'aws-svc-artifact', 'security.Shield': 'aws-svc-shield',
    'management.AmazonManagedPrometheus': 'aws-svc-managed-service-for-prometheus',
    'management.AmazonManagedWorkflowsApacheAirflow': 'aws-svc-managed-workflows-for-apache-airflow',
    'management.ManagementAndGovernance': 'aws-cat-management-tools',
    'management.PersonalHealthDashboard': 'aws-svc-health-dashboard', 'management.SystemsManagerAppConfig': 'aws-svc-appconfig',
    'management.AutoScaling': 'aws-svc-auto-scaling', 'management.OpsworksApps': { none: 'AWS OpsWorks shut down 2024-05-01' },
    'management.OpsworksDeployments': { none: 'AWS OpsWorks shut down 2024-05-01' }, 'management.OpsworksInstances': { none: 'AWS OpsWorks shut down 2024-05-01' },
    'management.OpsworksLayers': { none: 'AWS OpsWorks shut down 2024-05-01' }, 'management.OpsworksMonitoring': { none: 'AWS OpsWorks shut down 2024-05-01' },
    'management.OpsworksPermissions': { none: 'AWS OpsWorks shut down 2024-05-01' }, 'management.OpsworksResources': { none: 'AWS OpsWorks shut down 2024-05-01' },
    'management.OpsworksStack': { none: 'AWS OpsWorks shut down 2024-05-01' }, 'management.Opsworks': { none: 'AWS OpsWorks shut down 2024-05-01' },
    'analytics.Analytics': 'aws-cat-analytics', 'analytics.DataPipeline': { none: 'no icon in the AWS package' },
    'analytics.ElasticsearchService': 'aws-svc-opensearch-service', 'analytics.EMREngineMaprM3': 'aws-res-emr-engine',
    'analytics.EMREngineMaprM5': 'aws-res-emr-engine', 'analytics.EMREngineMaprM7': 'aws-res-emr-engine',
    'analytics.GlueCrawlers': 'aws-res-glue-crawler', 'analytics.KinesisDataAnalytics': 'aws-svc-managed-service-for-apache-flink',
    'analytics.KinesisDataFirehose': 'aws-svc-data-firehose',
    'analytics.ManagedStreamingForKafka': 'aws-svc-managed-streaming-for-apache-kafka', 'analytics.Quicksight': 'aws-svc-quick',
    'analytics.KinesisVideoStreams': 'aws-svc-kinesis-video-streams', 'devtools.Codestar': { none: 'AWS CodeStar shut down 2024-07-25' },
    'devtools.DeveloperTools': 'aws-cat-developer-tools', 'ml.AugmentedAi': 'aws-svc-augmented-ai-a2i',
    'ml.Deepcomposer': { none: 'AWS DeepComposer shut down' }, 'ml.Deeplens': { none: 'AWS DeepLens shut down 2024-01-31' },
    'ml.MachineLearning': 'aws-cat-artificial-intelligence', 'ml.SagemakerModel': 'aws-res-sagemaker-ai-model',
    'ml.SagemakerNotebook': 'aws-res-sagemaker-ai-notebook', 'ml.SagemakerTrainingJob': 'aws-res-sagemaker-ai-train',
    'general.General': { none: 'no icon in the AWS package' }, 'general.GenericDatabase': 'aws-res-database',
    'general.GenericFirewall': 'aws-res-firewall', 'general.GenericOfficeBuilding': 'aws-res-office-building',
    'general.GenericSamlToken': 'aws-res-saml-token', 'general.GenericSDK': 'aws-res-sdk',
    'general.Marketplace': 'aws-svc-marketplace', 'general.TraditionalServer': 'aws-res-server',
    'migration.CloudendureMigration': 'aws-svc-application-migration-service',
    'migration.MigrationAndTransfer': 'aws-cat-migration-modernization',
    'migration.MigrationHub': { none: 'AWS Migration Hub has no icon in the package' },
    'migration.ServerMigrationService': { none: 'AWS Server Migration Service shut down' }, 'migration.Snowmobile': { none: 'AWS Snowmobile shut down' },
    'migration.TransferForSftp': 'aws-res-transfer-family-sftp', 'mobile.Mobile': 'aws-cat-front-end-web-mobile',
    'iot.InternetOfThings': 'aws-cat-internet-of-things', 'iot.Iot1Click': { none: 'AWS IoT 1-Click shut down' },
    'iot.IotAlexaEcho': 'aws-res-iot-echo', 'iot.IotAnalyticsChannel': { none: 'AWS IoT Analytics shut down 2025-12-15' },
    'iot.IotAnalyticsDataSet': { none: 'AWS IoT Analytics shut down 2025-12-15' }, 'iot.IotAnalyticsDataStore': { none: 'AWS IoT Analytics shut down 2025-12-15' },
    'iot.IotAnalyticsNotebook': { none: 'AWS IoT Analytics shut down 2025-12-15' }, 'iot.IotAnalyticsPipeline': { none: 'AWS IoT Analytics shut down 2025-12-15' },
    'iot.IotAnalytics': { none: 'AWS IoT Analytics shut down 2025-12-15' }, 'iot.IotBank': 'aws-res-iot-thing-bank',
    'iot.IotBicycle': 'aws-res-iot-thing-bicycle', 'iot.IotButton': { none: 'no icon in the AWS package' },
    'iot.IotCamera': 'aws-res-iot-thing-camera', 'iot.IotCar': 'aws-res-iot-thing-car', 'iot.IotCart': 'aws-res-iot-thing-cart',
    'iot.IotCoffeePot': 'aws-res-iot-thing-coffee-pot', 'iot.IotDoorLock': 'aws-res-iot-thing-door-lock',
    'iot.IotFactory': 'aws-res-iot-thing-factory', 'iot.IotGeneric': 'aws-res-iot-thing-generic',
    'iot.IotHouse': 'aws-res-iot-thing-house', 'iot.IotHttp': 'aws-res-iot-http-protocol',
    'iot.IotHttp2': 'aws-res-iot-http2-protocol', 'iot.IotMqtt': 'aws-res-iot-mqtt-protocol',
    'iot.IotJobs': 'aws-res-iot-device-defender-iot-device-jobs', 'iot.IotLambda': 'aws-res-iot-lambda-function',
    'iot.IotLightbulb': 'aws-res-iot-thing-lightbulb', 'iot.IotMedicalEmergency': 'aws-res-iot-thing-medical-emergency',
    'iot.IotOverTheAirUpdate': 'aws-res-iot-over-air-update', 'iot.IotPolicyEmergency': 'aws-res-iot-thing-police-emergency',
    'iot.IotThermostat': 'aws-res-iot-thing-thermostat', 'iot.IotThingsGraph': { none: 'AWS IoT Things Graph shut down' },
    'iot.IotTravel': 'aws-res-iot-thing-travel', 'iot.IotUtility': 'aws-res-iot-thing-utility',
    'iot.IotWindfarm': 'aws-res-iot-thing-windfarm', 'media.ElasticTranscoder': { none: 'Amazon Elastic Transcoder shut down' },
    'media.MediaServices': 'aws-cat-media-services', 'business.AlexaForBusiness': { none: 'Alexa for Business shut down' },
    'business.BusinessApplications': 'aws-cat-business-applications', 'cost.CostManagement': 'aws-cat-cloud-financial-management',
    'engagement.CustomerEngagement': 'aws-cat-customer-experience', 'enduser.Appstream20': { none: 'AppStream 2.0 is now Amazon WorkSpaces Applications; no icon in the package' },
    'enduser.DesktopAndAppStreaming': 'aws-cat-end-user-computing', 'enduser.Worklink': { none: 'Amazon WorkLink shut down' },
    'blockchain.QuantumLedgerDatabaseQldb': { none: 'Amazon QLDB shut down 2025-07-31' }, 'blockchain.BlockchainResource': 'aws-res-managed-blockchain-blockchain',
    'enablement.CustomerEnablement': 'aws-cat-customer-enablement', 'game.GameTech': 'aws-cat-games',
    'game.Gamelift': 'aws-svc-gamelift-servers', 'quantum.QuantumTechnologies': 'aws-cat-quantum-technologies',
    'robotics.RobomakerCloudExtensionRos': { none: 'AWS RoboMaker shut down 2025-09-10' },
    'robotics.RobomakerDevelopmentEnvironment': { none: 'AWS RoboMaker shut down 2025-09-10' },
    'robotics.RobomakerFleetManagement': { none: 'AWS RoboMaker shut down 2025-09-10' }, 'robotics.RobomakerSimulator': { none: 'AWS RoboMaker shut down 2025-09-10' },
    'robotics.Robomaker': { none: 'AWS RoboMaker shut down 2025-09-10' }, 'robotics.Robotics': { none: 'no icon in the AWS package' },
    'satellite.Satellite': 'aws-cat-satellite', 'ar.ArVr': { none: 'no icon in the AWS package' },
    'ar.Sumerian': { none: 'Amazon Sumerian shut down' }, 'compute.ComputeOptimizer': 'aws-svc-compute-optimizer',
    'compute.EC2AutoScaling': 'aws-svc-ec2-auto-scaling', 'management.ManagementConsole': 'aws-svc-management-console',
    'devtools.Cloud9Resource': 'aws-res-cloud9', 'devtools.Cloud9': 'aws-svc-cloud9',
    'media.KinesisVideoStreams': 'aws-svc-kinesis-video-streams',
    // module aliases (from diagrams.aws.<module> import ALB): a static parse sees these names
    'compute.AutoScaling': 'aws-svc-application-auto-scaling', 'compute.AMI': 'aws-res-ec2-ami',
    'compute.ECR': 'aws-svc-elastic-container-registry', 'compute.EB': 'aws-svc-elastic-beanstalk',
    'compute.ECS': 'aws-svc-elastic-container-service', 'compute.EKS': 'aws-svc-elastic-kubernetes-service',
    'compute.SAR': 'aws-svc-serverless-application-repository', 'network.CF': 'aws-svc-cloudfront',
    'network.ELB': 'aws-svc-elastic-load-balancing', 'network.ALB': 'aws-res-elastic-load-balancing-application-load-balancer',
    'network.CLB': 'aws-res-elastic-load-balancing-classic-load-balancer',
    'network.NLB': 'aws-res-elastic-load-balancing-network-load-balancer', 'network.GAX': 'aws-svc-global-accelerator',
    'network.IGW': 'aws-res-vpc-internet-gateway', 'network.TGW': 'aws-svc-transit-gateway',
    'network.TGWAttach': 'aws-res-transit-gateway-attachment', 'database.DMS': 'aws-svc-database-migration-service',
    'database.DocumentDB': 'aws-svc-documentdb', 'database.DAX': 'aws-res-dynamodb-accelerator',
    'database.DynamodbGSI': 'aws-res-dynamodb-global-secondary-index', 'database.DB': 'aws-res-database',
    'database.DDB': 'aws-svc-dynamodb', 'database.ElastiCache': 'aws-svc-elasticache',
    'database.QLDB': { none: 'Amazon QLDB shut down 2025-07-31' }, 'storage.CDR': 'aws-svc-elastic-disaster-recovery',
    'storage.EBS': 'aws-svc-elastic-block-store', 'storage.EFS': 'aws-svc-efs', 'storage.FSx': 'aws-svc-fsx',
    'storage.S3': 'aws-svc-simple-storage-service', 'integration.SNS': 'aws-svc-simple-notification-service',
    'integration.SQS': 'aws-svc-simple-queue-service', 'integration.SF': 'aws-svc-step-functions',
    'security.ACM': 'aws-svc-certificate-manager', 'security.CloudHSM': 'aws-svc-cloudhsm',
    'security.DS': 'aws-svc-directory-service', 'security.FMS': 'aws-svc-firewall-manager',
    'security.IAMAccessAnalyzer': 'aws-res-identity-access-management-iam-access-analyzer',
    'security.IAMAWSSts': 'aws-res-identity-access-management-sts',
    'security.IAMPermissions': 'aws-res-identity-access-management-permissions',
    'security.IAMRole': 'aws-res-identity-access-management-role', 'security.IAM': 'aws-svc-identity-and-access-management',
    'security.KMS': 'aws-svc-key-management-service', 'security.RAM': 'aws-svc-resource-access-manager',
    'management.SSM': 'aws-svc-systems-manager', 'management.ParameterStore': 'aws-res-systems-manager-parameter-store',
    'analytics.ES': 'aws-svc-opensearch-service', 'devtools.CLI': 'aws-svc-command-line-interface',
    'devtools.DevTools': 'aws-cat-developer-tools', 'ml.DLC': 'aws-svc-deep-learning-containers',
    'migration.ADS': 'aws-svc-application-discovery-service', 'migration.CEM': 'aws-svc-application-migration-service',
    'migration.DMS': 'aws-svc-database-migration-service', 'migration.MAT': 'aws-cat-migration-modernization',
    'migration.SMS': { none: 'AWS Server Migration Service shut down' }, 'iot.FreeRTOS': 'aws-svc-freertos',
    'iot.IotBoard': 'aws-res-iot-hardware-board', 'business.A4B': { none: 'Alexa for Business shut down' },
    'engagement.SES': 'aws-svc-simple-email-service', 'blockchain.QLDB': { none: 'Amazon QLDB shut down 2025-07-31' },
  },
  cfn: {
    // ---- EC2 / VPC
    'AWS::EC2::Instance': 'aws-res-ec2-instance',
    'AWS::EC2::VPC': { group: 'vpc' },
    'AWS::EC2::Subnet': { group: 'priv', by: 'MapPublicIpOnLaunch', map: { true: { group: 'pub' } }, hint: 'public vs private comes from the route table (0.0.0.0/0 to an internet gateway = public)' },
    'AWS::EC2::SecurityGroup': { group: 'sg' },
    'AWS::EC2::SecurityGroupIngress': { role: 'edge' }, 'AWS::EC2::SecurityGroupEgress': { role: 'edge' },
    'AWS::EC2::InternetGateway': 'aws-res-vpc-internet-gateway',
    'AWS::EC2::EgressOnlyInternetGateway': { none: 'no egress-only internet gateway icon in the AWS package' },
    'AWS::EC2::VPCGatewayAttachment': { role: 'edge' },
    'AWS::EC2::NatGateway': 'aws-res-vpc-nat-gateway',
    'AWS::EC2::EIP': { role: 'attr', icon: 'aws-res-ec2-elastic-ip-address' },
    'AWS::EC2::RouteTable': { role: 'attr', icon: 'aws-res-route-53-route-table' },
    'AWS::EC2::Route': { role: 'edge' }, 'AWS::EC2::SubnetRouteTableAssociation': { role: 'edge' },
    'AWS::EC2::NetworkAcl': { role: 'attr', icon: 'aws-res-vpc-network-access-control-list' },
    'AWS::EC2::NetworkInterface': 'aws-res-vpc-elastic-network-interface',
    'AWS::EC2::VPCEndpoint': 'aws-res-vpc-endpoints',
    'AWS::EC2::VPCEndpointService': 'aws-svc-privatelink',
    'AWS::EC2::VPCPeeringConnection': 'aws-res-vpc-peering-connection',
    'AWS::EC2::TransitGateway': 'aws-svc-transit-gateway',
    'AWS::EC2::TransitGatewayAttachment': 'aws-res-transit-gateway-attachment',
    'AWS::EC2::TransitGatewayVpcAttachment': 'aws-res-transit-gateway-attachment',
    'AWS::EC2::TransitGatewayRouteTable': { role: 'attr' },
    'AWS::EC2::VPNGateway': 'aws-res-vpc-vpn-gateway',
    'AWS::EC2::CustomerGateway': 'aws-res-vpc-customer-gateway',
    'AWS::EC2::VPNConnection': 'aws-res-vpc-vpn-connection',
    'AWS::EC2::FlowLog': 'aws-res-vpc-flow-logs',
    'AWS::EC2::Volume': 'aws-res-elastic-block-store-volume',
    'AWS::EC2::LaunchTemplate': { role: 'attr' },
    'AWS::EC2::KeyPair': { role: 'meta' }, 'AWS::EC2::DHCPOptions': { role: 'meta' },
    'AWS::EC2::PlacementGroup': { role: 'attr' },
    'AWS::EC2::SpotFleet': { group: 'spot' },
    'AWS::EC2::CarrierGateway': 'aws-res-vpc-carrier-gateway',
    'AWS::EC2::TrafficMirrorSession': 'aws-res-vpc-traffic-mirroring',
    'AWS::EC2::NetworkInsightsPath': 'aws-res-vpc-reachability-analyzer',
    // ---- load balancing / scaling
    'AWS::ElasticLoadBalancingV2::LoadBalancer': { icon: 'aws-res-elastic-load-balancing-application-load-balancer', by: 'Type', map: { application: 'aws-res-elastic-load-balancing-application-load-balancer', network: 'aws-res-elastic-load-balancing-network-load-balancer', gateway: 'aws-res-elastic-load-balancing-gateway-load-balancer' } },
    'AWS::ElasticLoadBalancingV2::TargetGroup': { role: 'attr' },
    'AWS::ElasticLoadBalancingV2::Listener': { role: 'edge' }, 'AWS::ElasticLoadBalancingV2::ListenerRule': { role: 'edge' },
    'AWS::ElasticLoadBalancing::LoadBalancer': 'aws-res-elastic-load-balancing-classic-load-balancer',
    'AWS::AutoScaling::AutoScalingGroup': { group: 'asg' },
    'AWS::AutoScaling::LaunchConfiguration': { role: 'attr' }, 'AWS::AutoScaling::ScalingPolicy': { role: 'attr' },
    'AWS::ApplicationAutoScaling::ScalableTarget': { role: 'attr', icon: 'aws-svc-application-auto-scaling' },
    // ---- compute / containers / serverless (Lambda functions and DynamoDB tables draw as their service icon by default)
    'AWS::Lambda::Function': 'aws-res-lambda-function',
    'AWS::Lambda::Permission': { role: 'edge' }, 'AWS::Lambda::EventSourceMapping': { role: 'edge' },
    'AWS::Lambda::LayerVersion': { role: 'attr' }, 'AWS::Lambda::Url': { role: 'attr' },
    'AWS::Lambda::Alias': { role: 'attr' }, 'AWS::Lambda::Version': { role: 'attr' },
    'AWS::Serverless::Function': 'aws-res-lambda-function',
    'AWS::Serverless::Api': 'aws-svc-api-gateway', 'AWS::Serverless::HttpApi': 'aws-svc-api-gateway',
    'AWS::Serverless::StateMachine': 'aws-svc-step-functions',
    'AWS::Serverless::SimpleTable': 'aws-res-dynamodb-table',
    'AWS::Serverless::LayerVersion': { role: 'attr' },
    'AWS::Batch::ComputeEnvironment': 'aws-svc-batch',
    'AWS::ECS::Cluster': { group: 'gen', icon: 'aws-svc-elastic-container-service' },
    'AWS::ECS::Service': 'aws-res-elastic-container-service-service',
    'AWS::ECS::TaskDefinition': 'aws-res-elastic-container-service-task',
    'AWS::ECR::Repository': 'aws-res-elastic-container-registry-registry',
    'AWS::EKS::Cluster': { group: 'gen', icon: 'aws-svc-elastic-kubernetes-service' },
    'AWS::EKS::Nodegroup': 'aws-res-ec2-instances',
    'AWS::EKS::FargateProfile': 'aws-svc-fargate',
    'AWS::AppRunner::Service': 'aws-svc-app-runner',
    'AWS::ElasticBeanstalk::Environment': 'aws-res-elastic-beanstalk-deployment',
    'AWS::ElasticBeanstalk::Application': 'aws-res-elastic-beanstalk-application',
    'AWS::Lightsail::Instance': 'aws-svc-lightsail',
    // ---- storage / database
    'AWS::S3::Bucket': 'aws-res-simple-storage-service-bucket',
    'AWS::S3::BucketPolicy': { role: 'attr' },
    'AWS::EFS::FileSystem': 'aws-res-elastic-file-system-file-system',
    'AWS::EFS::MountTarget': { role: 'edge' },
    'AWS::FSx::FileSystem': { icon: 'aws-svc-fsx', by: 'FileSystemType', map: { lustre: 'aws-svc-fsx-for-lustre', ontap: 'aws-svc-fsx-for-netapp-ontap', openzfs: 'aws-svc-fsx-for-openzfs', windows: 'aws-svc-fsx-for-wfs' } },
    'AWS::Backup::BackupPlan': 'aws-res-backup-plan',
    'AWS::Backup::BackupVault': 'aws-res-backup-vault',
    'AWS::RDS::DBInstance': { icon: 'aws-res-aurora-rds-instance', by: 'Engine', standby: 'MultiAZ', map: { mysql: 'aws-res-aurora-mysql-instance', postgres: 'aws-res-aurora-postgresql-instance', mariadb: 'aws-res-aurora-mariadb-instance', oracle: 'aws-res-aurora-oracle-instance', 'custom-oracle': 'aws-res-aurora-oracle-instance', sqlserver: 'aws-res-aurora-sql-server-instance', 'custom-sqlserver': 'aws-res-aurora-sql-server-instance', aurora: 'aws-res-aurora-instance', 'aurora-mysql': 'aws-res-aurora-mysql-instance', 'aurora-postgresql': 'aws-res-aurora-postgresql-instance' } },
    'AWS::RDS::DBCluster': { icon: 'aws-svc-aurora', by: 'Engine', map: { aurora: 'aws-svc-aurora', mysql: 'aws-res-rds-multi-az-db-cluster', postgres: 'aws-res-rds-multi-az-db-cluster' } },
    'AWS::RDS::DBSubnetGroup': { role: 'attr' },
    'AWS::RDS::DBProxy': 'aws-res-rds-proxy-instance',
    'AWS::DynamoDB::Table': 'aws-res-dynamodb-table',
    'AWS::DynamoDB::GlobalTable': 'aws-svc-dynamodb',
    'AWS::ElastiCache::ReplicationGroup': { icon: 'aws-res-elasticache-for-redis', by: 'Engine', map: { redis: 'aws-res-elasticache-for-redis', valkey: 'aws-res-elasticache-for-valkey', memcached: 'aws-res-elasticache-for-memcached' } },
    'AWS::ElastiCache::CacheCluster': { icon: 'aws-res-elasticache-cache-node', by: 'Engine', map: { redis: 'aws-res-elasticache-for-redis', valkey: 'aws-res-elasticache-for-valkey', memcached: 'aws-res-elasticache-for-memcached' } },
    'AWS::ElastiCache::ServerlessCache': { icon: 'aws-svc-elasticache', by: 'Engine', map: { redis: 'aws-res-elasticache-for-redis', valkey: 'aws-res-elasticache-for-valkey', memcached: 'aws-res-elasticache-for-memcached' } },
    'AWS::DocDB::DBCluster': 'aws-svc-documentdb',
    'AWS::Neptune::DBCluster': 'aws-svc-neptune',
    'AWS::MemoryDB::Cluster': 'aws-svc-memorydb',
    'AWS::Redshift::Cluster': 'aws-svc-redshift',
    'AWS::OpenSearchService::Domain': 'aws-svc-opensearch-service',
    'AWS::Elasticsearch::Domain': 'aws-svc-opensearch-service',   // legacy type of the renamed service
    'AWS::Timestream::Database': 'aws-svc-timestream',
    'AWS::QLDB::Ledger': { none: 'Amazon QLDB shut down 2025-07-31' },
    // ---- integration / eventing (SQS queues and SNS topics draw as their service icon by default)
    'AWS::SQS::Queue': 'aws-res-simple-queue-service-queue',
    'AWS::SQS::QueuePolicy': { role: 'attr' },
    'AWS::SNS::Topic': 'aws-res-simple-notification-service-topic',
    'AWS::SNS::Subscription': { role: 'edge' }, 'AWS::SNS::TopicPolicy': { role: 'attr' },
    'AWS::Events::Rule': 'aws-res-eventbridge-rule',
    'AWS::Events::EventBus': 'aws-res-eventbridge-custom-event-bus',
    'AWS::Scheduler::Schedule': 'aws-res-eventbridge-scheduler',
    'AWS::Pipes::Pipe': 'aws-res-eventbridge-pipes',
    'AWS::StepFunctions::StateMachine': 'aws-svc-step-functions',
    'AWS::ApiGateway::RestApi': 'aws-svc-api-gateway',
    'AWS::ApiGateway::Method': { role: 'edge' },
    'AWS::ApiGateway::Resource': { role: 'attr' }, 'AWS::ApiGateway::Deployment': { role: 'attr' }, 'AWS::ApiGateway::Stage': { role: 'attr' },
    'AWS::ApiGatewayV2::Api': 'aws-svc-api-gateway',
    'AWS::AppSync::GraphQLApi': 'aws-svc-appsync',
    'AWS::MSK::Cluster': 'aws-svc-managed-streaming-for-apache-kafka',
    'AWS::AmazonMQ::Broker': 'aws-res-mq-broker',
    'AWS::Kinesis::Stream': 'aws-svc-kinesis-data-streams',
    'AWS::KinesisFirehose::DeliveryStream': 'aws-svc-data-firehose',
    // ---- network edge / DNS / security
    'AWS::CloudFront::Distribution': 'aws-res-cloudfront-download-distribution',
    'AWS::CloudFront::Function': 'aws-res-cloudfront-functions',
    'AWS::Route53::HostedZone': 'aws-res-route-53-hosted-zone',
    'AWS::Route53::RecordSet': { role: 'edge' }, 'AWS::Route53::RecordSetGroup': { role: 'edge' },
    'AWS::Route53::HealthCheck': { role: 'attr' },
    'AWS::Route53Resolver::ResolverEndpoint': 'aws-res-route-53-resolver',
    'AWS::Route53Resolver::ResolverRule': { role: 'attr' },
    'AWS::Route53Resolver::FirewallRuleGroup': 'aws-res-route-53-resolver-dns-firewall',
    'AWS::WAFv2::WebACL': 'aws-svc-waf',
    'AWS::Shield::Protection': 'aws-svc-shield',
    'AWS::NetworkFirewall::Firewall': 'aws-svc-network-firewall',
    'AWS::GlobalAccelerator::Accelerator': 'aws-svc-global-accelerator',
    'AWS::VpcLattice::Service': 'aws-svc-vpc-lattice',
    'AWS::VerifiedAccess::Instance': 'aws-svc-verified-access',
    'AWS::DirectConnect::Gateway': 'aws-res-direct-connect-gateway',
    'AWS::Cognito::UserPool': 'aws-svc-cognito',
    'AWS::ACM::Certificate': 'aws-svc-certificate-manager',
    'AWS::KMS::Key': 'aws-svc-key-management-service',
    'AWS::KMS::Alias': { role: 'attr' },
    'AWS::SecretsManager::Secret': 'aws-svc-secrets-manager',
    'AWS::SSM::Parameter': 'aws-res-systems-manager-parameter-store',
    'AWS::IAM::Role': 'aws-res-identity-access-management-role',
    'AWS::IAM::Policy': { role: 'attr', icon: 'aws-res-identity-access-management-permissions' },
    'AWS::IAM::ManagedPolicy': { role: 'attr', icon: 'aws-res-identity-access-management-permissions' },
    'AWS::IAM::InstanceProfile': { role: 'attr' },
    'AWS::IAM::User': 'aws-res-user',
    'AWS::GuardDuty::Detector': 'aws-svc-guardduty',
    'AWS::SecurityHub::Hub': 'aws-svc-security-hub',
    'AWS::Config::ConfigRule': 'aws-svc-config',
    'AWS::CloudTrail::Trail': 'aws-svc-cloudtrail',
    'AWS::DirectoryService::MicrosoftAD': 'aws-res-directory-service-managed-microsoft-ad',
    'AWS::DirectoryService::SimpleAD': 'aws-res-directory-service-simple-ad',
    'AWS::Organizations::Account': 'aws-res-organizations-account',
    'AWS::Organizations::OrganizationalUnit': 'aws-res-organizations-organizational-unit',
    // ---- observability / management / developer tools
    'AWS::Logs::LogGroup': 'aws-res-cloudwatch-logs',
    'AWS::CloudWatch::Alarm': 'aws-res-cloudwatch-alarm',
    'AWS::CloudWatch::Dashboard': 'aws-svc-cloudwatch',
    'AWS::CloudFormation::Stack': 'aws-res-cloudformation-stack',
    'AWS::CloudFormation::CustomResource': { role: 'meta' }, 'AWS::CDK::Metadata': { role: 'meta' },
    'AWS::CodePipeline::Pipeline': 'aws-svc-codepipeline',
    'AWS::CodeBuild::Project': 'aws-svc-codebuild',
    'AWS::CodeCommit::Repository': 'aws-svc-codecommit',
    'AWS::CodeDeploy::DeploymentGroup': 'aws-svc-codedeploy',
    'AWS::Cloud9::EnvironmentEC2': 'aws-res-cloud9',
    'AWS::OpsWorks::Stack': { none: 'AWS OpsWorks shut down 2024-05-01' },
    'AWS::CodeStar::GitHubRepository': { none: 'AWS CodeStar shut down 2024-07-25' },
    'AWS::Glue::Database': 'aws-res-glue-data-catalog',
    'AWS::Glue::Crawler': 'aws-res-glue-crawler',
    'AWS::Glue::Job': 'aws-svc-glue',
    'AWS::Athena::WorkGroup': 'aws-svc-athena',
    'AWS::LakeFormation::Resource': 'aws-res-lake-formation-data-lake',
    'AWS::EMR::Cluster': 'aws-res-emr-cluster',
    'AWS::SageMaker::NotebookInstance': 'aws-res-sagemaker-ai-notebook',
    'AWS::SageMaker::Endpoint': 'aws-svc-sagemaker-ai',
    'AWS::SageMaker::Model': 'aws-res-sagemaker-ai-model',
    'AWS::Bedrock::Agent': 'aws-svc-bedrock',
    'AWS::DMS::ReplicationInstance': 'aws-svc-database-migration-service',
    'AWS::DataSync::Task': 'aws-svc-datasync',
    'AWS::Transfer::Server': 'aws-svc-transfer-family',
    'AWS::SES::EmailIdentity': 'aws-svc-simple-email-service',
    'AWS::Pinpoint::App': 'aws-svc-pinpoint',
    'AWS::Connect::Instance': 'aws-svc-connect',
    'AWS::WorkSpaces::Workspace': 'aws-svc-workspaces',
    'AWS::AppStream::Fleet': { none: 'AppStream 2.0 is now Amazon WorkSpaces Applications; no icon in the AWS package' },
    'AWS::IoT::Thing': 'aws-res-iot-thing-generic',
    'AWS::IoT::TopicRule': 'aws-res-iot-rule',
    'AWS::Amplify::App': 'aws-svc-amplify',
    'AWS::MediaConvert::Queue': 'aws-svc-elemental-mediaconvert',
  },
  // Terraform AWS provider types for the same resources as the cfn table. The names are not mechanical
  // (aws_instance, aws_lb, aws_db_instance, aws_cloudwatch_event_rule...), so every one is listed.
  tf: {
    // ---- EC2 / VPC
    aws_instance: 'aws-res-ec2-instance',
    aws_vpc: { group: 'vpc' },
    aws_subnet: { group: 'priv', by: 'map_public_ip_on_launch', map: { true: { group: 'pub' } }, hint: 'public vs private comes from the route table (0.0.0.0/0 to an internet gateway = public)' },
    aws_default_subnet: { group: 'pub' },
    aws_security_group: { group: 'sg' },
    aws_security_group_rule: { role: 'edge' }, aws_vpc_security_group_ingress_rule: { role: 'edge' }, aws_vpc_security_group_egress_rule: { role: 'edge' },
    aws_internet_gateway: 'aws-res-vpc-internet-gateway',
    aws_egress_only_internet_gateway: { none: 'no egress-only internet gateway icon in the AWS package' },
    aws_internet_gateway_attachment: { role: 'edge' }, aws_vpn_gateway_attachment: { role: 'edge' },
    aws_nat_gateway: 'aws-res-vpc-nat-gateway',
    aws_eip: { role: 'attr', icon: 'aws-res-ec2-elastic-ip-address' },
    aws_route_table: { role: 'attr', icon: 'aws-res-route-53-route-table' },
    aws_route: { role: 'edge' }, aws_route_table_association: { role: 'edge' },
    aws_network_acl: { role: 'attr', icon: 'aws-res-vpc-network-access-control-list' },
    aws_network_interface: 'aws-res-vpc-elastic-network-interface',
    aws_vpc_endpoint: 'aws-res-vpc-endpoints',
    aws_vpc_endpoint_service: 'aws-svc-privatelink',
    aws_vpc_peering_connection: 'aws-res-vpc-peering-connection',
    aws_ec2_transit_gateway: 'aws-svc-transit-gateway',
    aws_ec2_transit_gateway_vpc_attachment: 'aws-res-transit-gateway-attachment',
    aws_ec2_transit_gateway_route_table: { role: 'attr' },
    aws_vpn_gateway: 'aws-res-vpc-vpn-gateway',
    aws_customer_gateway: 'aws-res-vpc-customer-gateway',
    aws_vpn_connection: 'aws-res-vpc-vpn-connection',
    aws_flow_log: 'aws-res-vpc-flow-logs',
    aws_ebs_volume: 'aws-res-elastic-block-store-volume',
    aws_launch_template: { role: 'attr' }, aws_placement_group: { role: 'attr' },
    aws_key_pair: { role: 'meta' }, aws_vpc_dhcp_options: { role: 'meta' },
    aws_spot_fleet_request: { group: 'spot' },
    aws_ec2_carrier_gateway: 'aws-res-vpc-carrier-gateway',
    aws_ec2_traffic_mirror_session: 'aws-res-vpc-traffic-mirroring',
    aws_ec2_network_insights_path: 'aws-res-vpc-reachability-analyzer',
    // ---- load balancing / scaling
    aws_lb: { icon: 'aws-res-elastic-load-balancing-application-load-balancer', by: 'load_balancer_type', map: { application: 'aws-res-elastic-load-balancing-application-load-balancer', network: 'aws-res-elastic-load-balancing-network-load-balancer', gateway: 'aws-res-elastic-load-balancing-gateway-load-balancer' } },
    aws_alb: 'aws-res-elastic-load-balancing-application-load-balancer',
    aws_lb_target_group: { role: 'attr' }, aws_alb_target_group: { role: 'attr' },
    aws_lb_listener: { role: 'edge' }, aws_alb_listener: { role: 'edge' }, aws_lb_listener_rule: { role: 'edge' },
    aws_elb: 'aws-res-elastic-load-balancing-classic-load-balancer',
    aws_autoscaling_group: { group: 'asg' },
    aws_launch_configuration: { role: 'attr' }, aws_autoscaling_policy: { role: 'attr' },
    aws_appautoscaling_target: { role: 'attr', icon: 'aws-svc-application-auto-scaling' },
    // ---- compute / containers / serverless
    aws_lambda_function: 'aws-res-lambda-function',
    aws_lambda_permission: { role: 'edge' }, aws_lambda_event_source_mapping: { role: 'edge' },
    aws_lambda_layer_version: { role: 'attr' }, aws_lambda_function_url: { role: 'attr' }, aws_lambda_alias: { role: 'attr' },
    aws_batch_compute_environment: 'aws-svc-batch',
    aws_ecs_cluster: { group: 'gen', icon: 'aws-svc-elastic-container-service' },
    aws_ecs_service: 'aws-res-elastic-container-service-service',
    aws_ecs_task_definition: 'aws-res-elastic-container-service-task',
    aws_ecr_repository: 'aws-res-elastic-container-registry-registry',
    aws_eks_cluster: { group: 'gen', icon: 'aws-svc-elastic-kubernetes-service' },
    aws_eks_node_group: 'aws-res-ec2-instances',
    aws_eks_fargate_profile: 'aws-svc-fargate',
    aws_apprunner_service: 'aws-svc-app-runner',
    aws_elastic_beanstalk_environment: 'aws-res-elastic-beanstalk-deployment',
    aws_elastic_beanstalk_application: 'aws-res-elastic-beanstalk-application',
    aws_lightsail_instance: 'aws-svc-lightsail',
    // ---- storage / database
    aws_s3_bucket: 'aws-res-simple-storage-service-bucket',
    aws_s3_bucket_policy: { role: 'attr' }, aws_s3_bucket_versioning: { role: 'attr' }, aws_s3_bucket_notification: { role: 'edge' },
    aws_efs_file_system: 'aws-res-elastic-file-system-file-system',
    aws_efs_mount_target: { role: 'edge' },
    aws_fsx_lustre_file_system: 'aws-svc-fsx-for-lustre',
    aws_fsx_ontap_file_system: 'aws-svc-fsx-for-netapp-ontap',
    aws_fsx_openzfs_file_system: 'aws-svc-fsx-for-openzfs',
    aws_fsx_windows_file_system: 'aws-svc-fsx-for-wfs',
    aws_backup_plan: 'aws-res-backup-plan',
    aws_backup_vault: 'aws-res-backup-vault',
    aws_db_instance: { icon: 'aws-res-aurora-rds-instance', by: 'engine', standby: 'multi_az', map: { mysql: 'aws-res-aurora-mysql-instance', postgres: 'aws-res-aurora-postgresql-instance', mariadb: 'aws-res-aurora-mariadb-instance', oracle: 'aws-res-aurora-oracle-instance', 'custom-oracle': 'aws-res-aurora-oracle-instance', sqlserver: 'aws-res-aurora-sql-server-instance', 'custom-sqlserver': 'aws-res-aurora-sql-server-instance' } },
    aws_rds_cluster_instance: { icon: 'aws-res-aurora-instance', by: 'engine', map: { aurora: 'aws-res-aurora-instance', 'aurora-mysql': 'aws-res-aurora-mysql-instance', 'aurora-postgresql': 'aws-res-aurora-postgresql-instance' } },
    aws_rds_cluster: { icon: 'aws-svc-aurora', by: 'engine', map: { aurora: 'aws-svc-aurora', mysql: 'aws-res-rds-multi-az-db-cluster', postgres: 'aws-res-rds-multi-az-db-cluster' } },
    aws_db_subnet_group: { role: 'attr' },
    aws_db_proxy: 'aws-res-rds-proxy-instance',
    aws_dynamodb_table: 'aws-res-dynamodb-table',
    aws_dynamodb_global_table: 'aws-svc-dynamodb',
    aws_dax_cluster: 'aws-res-dynamodb-accelerator',
    aws_elasticache_replication_group: { icon: 'aws-res-elasticache-for-redis', by: 'engine', map: { redis: 'aws-res-elasticache-for-redis', valkey: 'aws-res-elasticache-for-valkey' } },
    aws_elasticache_cluster: { icon: 'aws-res-elasticache-cache-node', by: 'engine', map: { redis: 'aws-res-elasticache-for-redis', valkey: 'aws-res-elasticache-for-valkey', memcached: 'aws-res-elasticache-for-memcached' } },
    aws_elasticache_serverless_cache: { icon: 'aws-svc-elasticache', by: 'engine', map: { redis: 'aws-res-elasticache-for-redis', valkey: 'aws-res-elasticache-for-valkey', memcached: 'aws-res-elasticache-for-memcached' } },
    aws_docdb_cluster: 'aws-svc-documentdb',
    aws_neptune_cluster: 'aws-svc-neptune',
    aws_memorydb_cluster: 'aws-svc-memorydb',
    aws_redshift_cluster: 'aws-svc-redshift',
    aws_opensearch_domain: 'aws-svc-opensearch-service',
    aws_elasticsearch_domain: 'aws-svc-opensearch-service',
    aws_timestreamwrite_database: 'aws-svc-timestream',
    aws_qldb_ledger: { none: 'Amazon QLDB shut down 2025-07-31' },
    // ---- integration / eventing
    aws_sqs_queue: 'aws-res-simple-queue-service-queue',
    aws_sqs_queue_policy: { role: 'attr' },
    aws_sns_topic: 'aws-res-simple-notification-service-topic',
    aws_sns_topic_subscription: { role: 'edge' }, aws_sns_topic_policy: { role: 'attr' },
    aws_cloudwatch_event_rule: 'aws-res-eventbridge-rule',
    aws_cloudwatch_event_bus: 'aws-res-eventbridge-custom-event-bus',
    aws_cloudwatch_event_target: { role: 'edge' },
    aws_scheduler_schedule: 'aws-res-eventbridge-scheduler',
    aws_pipes_pipe: 'aws-res-eventbridge-pipes',
    aws_sfn_state_machine: 'aws-svc-step-functions',
    aws_api_gateway_rest_api: 'aws-svc-api-gateway',
    aws_api_gateway_method: { role: 'edge' }, aws_api_gateway_integration: { role: 'edge' },
    aws_api_gateway_resource: { role: 'attr' }, aws_api_gateway_deployment: { role: 'attr' }, aws_api_gateway_stage: { role: 'attr' },
    aws_apigatewayv2_api: 'aws-svc-api-gateway',
    aws_apigatewayv2_integration: { role: 'edge' }, aws_apigatewayv2_route: { role: 'attr' }, aws_apigatewayv2_stage: { role: 'attr' },
    aws_appsync_graphql_api: 'aws-svc-appsync',
    aws_msk_cluster: 'aws-svc-managed-streaming-for-apache-kafka',
    aws_mq_broker: 'aws-res-mq-broker',
    aws_kinesis_stream: 'aws-svc-kinesis-data-streams',
    aws_kinesis_firehose_delivery_stream: 'aws-svc-data-firehose',
    // ---- network edge / DNS / security
    aws_cloudfront_distribution: 'aws-res-cloudfront-download-distribution',
    aws_cloudfront_function: 'aws-res-cloudfront-functions',
    aws_route53_zone: 'aws-res-route-53-hosted-zone',
    aws_route53_record: { role: 'edge' },
    aws_route53_health_check: { role: 'attr' },
    aws_route53_resolver_endpoint: 'aws-res-route-53-resolver',
    aws_route53_resolver_rule: { role: 'attr' },
    aws_route53_resolver_firewall_rule_group: 'aws-res-route-53-resolver-dns-firewall',
    aws_route53_resolver_query_log_config: 'aws-res-route-53-resolver-query-logging',
    aws_wafv2_web_acl: 'aws-svc-waf',
    aws_shield_protection: 'aws-svc-shield',
    aws_networkfirewall_firewall: 'aws-svc-network-firewall',
    aws_globalaccelerator_accelerator: 'aws-svc-global-accelerator',
    aws_vpclattice_service: 'aws-svc-vpc-lattice',
    aws_verifiedaccess_instance: 'aws-svc-verified-access',
    aws_dx_gateway: 'aws-res-direct-connect-gateway',
    aws_dx_connection: 'aws-svc-direct-connect',
    aws_cognito_user_pool: 'aws-svc-cognito',
    aws_acm_certificate: 'aws-svc-certificate-manager',
    aws_kms_key: 'aws-svc-key-management-service',
    aws_kms_alias: { role: 'attr' },
    aws_secretsmanager_secret: 'aws-svc-secrets-manager',
    aws_ssm_parameter: 'aws-res-systems-manager-parameter-store',
    aws_iam_role: 'aws-res-identity-access-management-role',
    aws_iam_policy: { role: 'attr', icon: 'aws-res-identity-access-management-permissions' },
    aws_iam_role_policy: { role: 'attr', icon: 'aws-res-identity-access-management-permissions' },
    aws_iam_role_policy_attachment: { role: 'edge' },
    aws_iam_instance_profile: { role: 'attr' },
    aws_iam_user: 'aws-res-user',
    aws_guardduty_detector: 'aws-svc-guardduty',
    aws_securityhub_account: 'aws-svc-security-hub',
    aws_config_config_rule: 'aws-svc-config',
    aws_cloudtrail: 'aws-svc-cloudtrail',
    aws_directory_service_directory: { icon: 'aws-res-directory-service-simple-ad', by: 'type', map: { microsoftad: 'aws-res-directory-service-managed-microsoft-ad', adconnector: 'aws-res-directory-service-ad-connector', simplead: 'aws-res-directory-service-simple-ad' } },
    aws_organizations_account: 'aws-res-organizations-account',
    aws_organizations_organizational_unit: 'aws-res-organizations-organizational-unit',
    // ---- observability / management / developer tools
    aws_cloudwatch_log_group: 'aws-res-cloudwatch-logs',
    aws_cloudwatch_metric_alarm: 'aws-res-cloudwatch-alarm',
    aws_cloudwatch_dashboard: 'aws-svc-cloudwatch',
    aws_cloudformation_stack: 'aws-res-cloudformation-stack',
    aws_codepipeline: 'aws-svc-codepipeline',
    aws_codebuild_project: 'aws-svc-codebuild',
    aws_codecommit_repository: 'aws-svc-codecommit',
    aws_codedeploy_deployment_group: 'aws-svc-codedeploy',
    aws_cloud9_environment_ec2: 'aws-res-cloud9',
    aws_glue_catalog_database: 'aws-res-glue-data-catalog',
    aws_glue_crawler: 'aws-res-glue-crawler',
    aws_glue_job: 'aws-svc-glue',
    aws_athena_workgroup: 'aws-svc-athena',
    aws_lakeformation_resource: 'aws-res-lake-formation-data-lake',
    aws_emr_cluster: 'aws-res-emr-cluster',
    aws_sagemaker_notebook_instance: 'aws-res-sagemaker-ai-notebook',
    aws_sagemaker_endpoint: 'aws-svc-sagemaker-ai',
    aws_sagemaker_model: 'aws-res-sagemaker-ai-model',
    aws_bedrockagent_agent: 'aws-svc-bedrock',
    aws_dms_replication_instance: 'aws-svc-database-migration-service',
    aws_datasync_task: 'aws-svc-datasync',
    aws_transfer_server: 'aws-svc-transfer-family',
    aws_sesv2_email_identity: 'aws-svc-simple-email-service', aws_ses_email_identity: 'aws-svc-simple-email-service',
    aws_pinpoint_app: 'aws-svc-pinpoint',
    aws_connect_instance: 'aws-svc-connect',
    aws_workspaces_workspace: 'aws-svc-workspaces',
    aws_appstream_fleet: { none: 'AppStream 2.0 is now Amazon WorkSpaces Applications; no icon in the AWS package' },
    aws_iot_thing: 'aws-res-iot-thing-generic',
    aws_iot_topic_rule: 'aws-res-iot-rule',
    aws_amplify_app: 'aws-svc-amplify',
    aws_media_convert_queue: 'aws-svc-elemental-mediaconvert',
  },
};
